### ISSUE TITLE
User Registration Form Santitation

### ISSUE THREAD

**Issue by amiller68** [banyancomputer/tombolo#7]
Our User Registration is very broken. The following needs to happen:
Sanitize User Input on the Client side. So the Frontend should:
- make sure their email is valid
- make sure their password is reasonably strong (@laudiacay  do you have thoughts here?)
  - > 8 chars
  - certain number of special chars
  - etc.
  - There are probably good tools for this already (ex: https://www.npmjs.com/package/check-password-strength)
- make them enter a password twice and that both match each other
- make sure Full Name is reasonably RegExed (Might need to split this up into First Name, Last Name)
- make sure Company Name is reasonably RegExed (unclear)
- make sure JobTitle is reasonably regexed, or provide default options
- make sure Phone Number is formatted like a Phone Number

Add corresponding Firestore rules in `firebase/firestore.rules`.

**Comment by laudiacay** [comment]
how hard would it be just to do google based auth?

**Comment by laudiacay** [comment]
easier
